# Generated by Django 2.2.6 on 2019-11-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
