# Generated by Django 2.2.6 on 2019-11-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticias_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Noticia',
        ),
    ]
