# Generated by Django 2.2.6 on 2019-11-16 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_auto_20191116_0007'),
        ('noticias', '0005_noticia_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfiles.Perfil'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
