# Generated by Django 2.2.6 on 2019-11-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_auto_20191116_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='foto_id',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='perfil_id',
            new_name='perfil',
        ),
    ]
