# Generated by Django 2.2.6 on 2019-11-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_auto_20191116_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='titulo',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
