# Generated by Django 2.2.6 on 2019-11-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0010_auto_20191118_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='perfil_id',
            new_name='perfil',
        ),
    ]
