# Generated by Django 2.2.6 on 2019-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0011_auto_20191118_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='titulo',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
