# Generated by Django 2.2.6 on 2019-11-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0014_auto_20191128_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='foto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfiles.Foto'),
        ),
    ]
