# Generated by Django 2.2.6 on 2019-11-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0015_auto_20191128_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='foto_id',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='perfil_id',
            new_name='perfil',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='foto_id',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='perfil_id',
            new_name='perfil',
        ),
        migrations.RenameField(
            model_name='seguidor',
            old_name='perfil_id',
            new_name='perfil',
        ),
    ]
