# Generated by Django 2.2.6 on 2019-11-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0016_auto_20191128_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='prueba',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
