# Generated by Django 2.2.6 on 2019-11-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0017_perfil_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='prueba',
        ),
    ]
