# Generated by Django 2.2.6 on 2019-11-29 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0018_remove_perfil_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfiles.Perfil'),
        ),
    ]
