# Generated by Django 2.2.6 on 2019-11-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0021_auto_20191129_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seguidor',
            new_name='Seguidores',
        ),
    ]
