# Generated by Django 2.2.6 on 2019-11-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0022_auto_20191129_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguidores',
            old_name='perfil',
            new_name='seguido',
        ),
        migrations.RenameField(
            model_name='seguidores',
            old_name='followed_user_id',
            new_name='seguidor',
        ),
    ]
