# Generated by Django 2.2.6 on 2019-11-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0023_auto_20191129_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='seguidores',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/fotos'),
        ),
    ]
