# Generated by Django 2.2.6 on 2019-11-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_auto_20191116_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='foto',
            new_name='foto_id',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='perfil',
            new_name='perfil_id',
        ),
    ]
