# Generated by Django 2.2.6 on 2019-11-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticias_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/fotos'),
        ),
    ]
